-- UniLink: Final Professional Student Ecosystem Schema (PostgreSQL/Supabase)

-- 1. ENABLE GEOSPATIAL EXTENSIONS
CREATE EXTENSION IF NOT EXISTS postgis;

-- 2. PROFILES & ACADEMIC TRACKING
CREATE TABLE IF NOT EXISTS profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    name TEXT NOT NULL,
    surname TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    gender TEXT CHECK (gender IN ('Male', 'Female', 'Non-binary')),
    polytechnic TEXT NOT NULL,
    course TEXT NOT NULL,
    year_of_study INT DEFAULT 1, -- For Study Buddy Matching
    bio TEXT,
    avatar_url TEXT DEFAULT 'https://ui-avatars.com/api/?name=Student&background=7c3aed&color=fff',
    is_study_mode BOOLEAN DEFAULT FALSE,
    location GEOGRAPHY(POINT) DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. CAMPUS FEED & ANONYMOUS CONFESSIONS
CREATE TABLE IF NOT EXISTS posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    content TEXT NOT NULL,
    media_url TEXT,
    is_anonymous BOOLEAN DEFAULT FALSE, -- Enabling Anonymous Confessions
    likes_count INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. LOVE & MATCHING (Dating Logic)
CREATE TABLE IF NOT EXISTS swipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    swiper_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    swiped_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    is_like BOOLEAN DEFAULT FALSE,
    is_study_request BOOLEAN DEFAULT FALSE, -- For Study Buddy Mode
    unique(swiper_id, swiped_id)
);

CREATE TABLE IF NOT EXISTS matches (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_1 UUID REFERENCES profiles(id) ON DELETE CASCADE,
    user_2 UUID REFERENCES profiles(id) ON DELETE CASCADE,
    match_type TEXT DEFAULT 'dating', -- dating | study
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    unique(user_1, user_2)
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id UUID REFERENCES matches(id) ON DELETE CASCADE,
    sender_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. POLYTECHNIC EVENT HUB (Ticketing & RSVP)
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    location TEXT NOT NULL,
    event_date TIMESTAMP WITH TIME ZONE NOT NULL,
    ticket_price DECIMAL(10,2) DEFAULT 0.00,
    media_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS event_rsvps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    ticket_quantity INT DEFAULT 1,
    status TEXT DEFAULT 'confirmed', -- confirmed | cancelled
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    unique(event_id, user_id)
);

-- 6. NOTIFICATIONS
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    payload JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
